name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          clean: false
          
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      
      - name: Archive infrastructure artifacts for pulumi up
        uses: actions/upload-artifact@v3
        with:
          name: infra-artifact
          path: ./demo.infra

      - name: Archive code artifacts for deployment slot display
        uses: actions/upload-artifact@v3
        with:
          name: code-artifact
          path: ./demo.code